theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
g = { a = "code_action" } 
'}' = "goto_next_paragraph"
'{' = "goto_prev_paragraph"

[editor.cursor-shape]
insert = "bar"

[keys.insert]
'j'	= {k='normal_mode','j'={'k'=[':insert-output /bin/echo -n j','move_char_right','normal_mode']}}
